import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
process.chdir(root);
if(!['darwin','linux'].includes(process.platform))throw Error('На Windows используйте Docker или установите Arduino CLI вручную.');
const system=process.platform==='darwin'?'macOS':'Linux';
const architecture=process.arch==='arm64'?'ARM64':'64bit';
const run=(cmd,args)=>new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:'inherit'});p.on('error',reject);p.on('exit',c=>c?reject(Error(`${cmd}: ${c}`)):resolve());});
await mkdir('.tools',{recursive:true});
console.log('Загружаем официальный Arduino CLI…');
const response=await fetch(`https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_${system}_${architecture}.tar.gz`);
if(!response.ok)throw Error(`Загрузка Arduino CLI: HTTP ${response.status}`);
await writeFile('.tools/arduino-cli.tar.gz',new Uint8Array(await response.arrayBuffer()));
await run('tar',['-xzf','.tools/arduino-cli.tar.gz','-C','.tools']);
await writeFile('.tools/arduino-cli.yaml',JSON.stringify({directories:{data:path.resolve('.tools/data'),downloads:path.resolve('.tools/downloads'),user:path.resolve('.tools/user')},build_cache:{path:path.resolve('.tools/cache')}}));
await run('.tools/arduino-cli',['core','install','arduino:avr','--config-file','.tools/arduino-cli.yaml']);
await run('.tools/arduino-cli',['lib','install','Servo','LiquidCrystal','--config-file','.tools/arduino-cli.yaml']);
console.log('Готово. Запуск: node server.mjs');
