import '@wokwi/elements';
import {EditorView,keymap,lineNumbers,highlightActiveLine,drawSelection,highlightActiveLineGutter} from '@codemirror/view';
import {EditorState} from '@codemirror/state';
import {defaultKeymap,history,historyKeymap,indentWithTab} from '@codemirror/commands';
import {cpp} from '@codemirror/lang-cpp';
import {syntaxHighlighting,HighlightStyle,bracketMatching,indentOnInput} from '@codemirror/language';
import {tags} from '@lezer/highlight';
import {createIcons,icons} from 'lucide';
import {catalog,byId,groups,catalogIcons,catalogOrder} from './catalog.js';
import {showCompileError,launchFireworks,dismissError} from './effects.js';
import {updateAmbient,clearAmbient,mountAmbient} from './ambient.js';
import {routeWire,pointsToPath} from './routing.js';
import {showSuccessReaction,showFailureReaction,preloadReactions} from './reactions.js';
import {examples,makeProject} from './examples.js';
import {validateCircuit,loadHex} from './circuit.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name,cls='')=>`<i data-lucide="${name}" class="${cls}"></i>`;
const btn=(name,action,label,extra='')=>`<button class="icon-btn ${extra}" data-action="${action}" title="${label}" aria-label="${label}">${icon(name)}</button>`;
const uid=()=>crypto.randomUUID().slice(0,8);
let project=makeProject(),savedAt=null,selected=null,wireStart=null,wireColor='#d8f65d',zoom=1,offset={x:0,y:0},mode='select';
let draftCursor=null;
let worker=null,running=false,paused=false,compiling=false,runGeneration=0,seconds=0,compiler=false,hexFile=null,activePanel='serial',group='Все',search='',supportedOnly=false;
let sound=localStorage.getItem('volt.sound')!=='off',audioContext,buzzers={},inputs={},undos=[],redos=[],autosaveTimer;
let firmware=fetch('/firmware.json').then(r=>{if(!r.ok)throw Error('Готовые прошивки не загрузились.');return r.json();});
firmware.catch(()=>{});
try{const saved=JSON.parse(localStorage.getItem('volt.current'));if(saved){validateProject(saved);project=saved;}}catch{}
function validateProject(p){
 if(!p||p.version!==1||typeof p.code!=='string'||p.code.length>100000||typeof p.name!=='string'||p.name.length>100||!Array.isArray(p.parts)||p.parts.length>100||!Array.isArray(p.wires)||p.wires.length>300)throw Error('Файл проекта повреждён или имеет неподдерживаемый формат.');
 const ids=new Set();for(const part of p.parts){if(!byId[part.type]?.ready||typeof part.id!=='string'||!/^[\w-]{1,80}$/.test(part.id)||ids.has(part.id)||!Number.isFinite(part.x)||!Number.isFinite(part.y)||Math.abs(part.x)>5000||Math.abs(part.y)>5000)throw Error('В проекте есть неподдерживаемый компонент.');ids.add(part.id);part.attrs??={};}
 for(const w of p.wires)if(typeof w.from!=='string'||typeof w.to!=='string'||!ids.has(w.from.split(':')[0])||!ids.has(w.to.split(':')[0])||!/^#[\da-f]{6}$/i.test(w.color))throw Error('В проекте есть некорректное соединение.');
}
$('#app').innerHTML=`
 <header class="topbar"><a href="/" class="brand" aria-label="SIMduino lab — лаборатория Arduino"><img class="brand-mark" src="/favicon.svg" alt=""><span class="brand-wordmark"><span class="brand-name">SIMduino <span class="brand-lab">lab</span></span><span class="brand-credit">Inspired by Talanov</span></span></a><nav class="topnav"><button class="active" data-action="workspace">Рабочая область</button><button data-action="projects">Мои проекты</button><button data-action="examples">Примеры<span class="nav-badge">7</span></button></nav><div class="header-right"><span class="free-label">Arduino Uno · без подписки</span>${btn('volume-2','sound','Звуковые эффекты')}${btn('circle-help','help','Как пользоваться')}<span class="avatar" title="Локальное рабочее пространство">Я</span></div></header>
 <div class="projectbar"><div class="project-path">${btn('panel-left','palette','Показать компоненты','mobile-only')}<span class="project-symbol">${icon('circuit-board')}</span><span class="muted desktop-only">Лаборатория</span><span class="divider desktop-only">/</span><button id="project-name" data-action="rename"></button><span id="saved" class="save-status">Сохранено на устройстве</span></div><div class="project-actions"><button class="button ghost desktop-only" data-action="import">${icon('folder-input')}Открыть</button><button class="button secondary" data-action="save" aria-label="Сохранить проект">${icon('download')}<span>Сохранить</span></button><button class="button primary" id="run" data-action="run">${icon('play')}<span>Запустить</span><kbd>⌘ ↵</kbd></button></div></div>
 <main class="workspace"><aside class="palette"><div class="palette-head"><h2>Компоненты</h2><span id="catalog-count"></span></div><label class="search">${icon('search')}<input id="search" placeholder="Найти компонент…" autocomplete="off" aria-label="Поиск компонентов"><kbd>/</kbd></label><div class="filter-row"><select id="category" aria-label="Категория">${groups.map(g=>`<option>${g}</option>`).join('')}</select>${btn('sliders-horizontal','filter','Показать весь каталог Wokwi')}</div><div class="palette-section"><span id="list-label">ДЛЯ ВАШЕЙ СХЕМЫ</span><span id="ready-count">11 моделей</span></div><div id="component-list"></div><div class="palette-bottom"><span class="little-mark"><img src="/favicon.svg" class="s-mark" alt=""></span><div><strong>Готовые упражнения<br>для Arduino Uno</strong><button data-action="examples">Начать с примера ${icon('arrow-up-right')}</button></div></div><button class="catalog-link" data-action="catalog">Весь каталог и поддержка ${icon('arrow-up-right')}</button></aside>
 <section class="bench"><div class="pane-header"><div class="pane-title">${icon('workflow')}<h2>Схема</h2><span id="part-count" class="count-badge"></span></div><div class="pane-tools">${btn('undo-2','undo','Отменить изменение схемы')}${btn('redo-2','redo','Повторить изменение схемы')}<span class="tool-separator"></span>${btn('maximize','fit','Вписать схему в экран')}</div></div><div id="canvas" class="canvas"><div class="canvas-caption"><div class="eyebrow">ARDUINO PLAYGROUND</div><h1>Всё начинается<br>с искры<span>.</span></h1><p>Собирайте. Запускайте. Экспериментируйте.</p></div><div class="canvas-status"><span id="run-dot"></span><span id="canvas-status">Готово к запуску</span></div><div id="world"><svg id="wires" width="2000" height="1400" aria-label="Соединения схемы"></svg><div id="parts"></div></div><div id="inspector" hidden></div><div class="canvas-bottom"><div class="canvas-toolbox">${btn('mouse-pointer-2','select','Выбор и перемещение','active')}${btn('cable','wire','Соединить выводы')}<span class="tool-separator"></span><input type="color" id="wire-color" value="#d8f65d" title="Цвет новых проводов" aria-label="Цвет новых проводов"></div><div class="zoom-control">${btn('minus','zoom-out','Уменьшить')}<span id="zoom-label">100%</span>${btn('plus','zoom-in','Увеличить')}</div></div><div id="canvas-hint">Нажмите на два вывода, чтобы соединить их проводом</div></div><div class="board-strip"><span>${icon('cpu')}<strong>Arduino Uno</strong><span class="muted">ATmega328P</span></span><span class="board-spec">16 MHz<span>·</span>32 KB Flash</span></div></section>
 <section class="editor-pane"><div class="pane-header"><div class="file-tab">${icon('file-code-2')}<span>sketch.ino</span><span class="file-dot"></span></div><div class="pane-tools">${btn('file-up','hex','Загрузить прошивку HEX')}${btn('copy','copy','Скопировать код')}</div></div><div class="editor-toolbar"><span>C++ <span class="muted">/ Arduino</span></span><span id="compiler-label">Проверяем компилятор…</span></div><div id="editor"></div><div class="editor-status"><span id="cursor">Стр 1, стлб 1</span><span>UTF-8<span class="space-dot">·</span>2 пробела</span></div><section class="console"><div class="console-header"><div><button class="active" data-action="serial-panel">${icon('terminal')}Монитор порта</button><button data-action="logs-panel">Вывод <span id="log-count">0</span></button></div>${btn('trash-2','clear-console','Очистить консоль')}</div><div id="serial-output" class="console-output"><div class="console-empty"><span>›_</span><p>Здесь заговорит ваша плата</p><small>Используйте Serial.println() в коде</small></div></div><div id="build-output" class="console-output" hidden></div><form id="serial-form"><span>›</span><input id="serial-input" placeholder="Отправить в Serial…" aria-label="Сообщение в Serial" maxlength="500"><span class="baud">UART</span><button class="icon-btn" title="Отправить" aria-label="Отправить">${icon('corner-down-left')}</button></form></section></section></main>
 <footer class="statusbar"><div><span class="status-indicator"></span><span id="bottom-status">Локальное сохранение</span><span class="footer-separator">|</span><span id="wire-count">3 соединения</span></div><div><span id="simulation-time">00:00.000</span><span class="footer-separator">|</span><span>Uno · AVR</span><button data-action="about">SIMduino lab <span class="version">v0.1</span></button></div></footer><div class="mobile-view"><button class="active" data-action="view-circuit">${icon('workflow')}Схема</button><button data-action="view-code">${icon('code-2')}Код</button></div><input type="file" id="file-input" accept=".json" hidden><input type="file" id="hex-input" accept=".hex" hidden>`;

const theme=EditorView.theme({'&':{height:'100%',backgroundColor:'#1b1d20',color:'#d7dbe1',fontSize:'14px'},'.cm-scroller':{fontFamily:'"SFMono-Regular",Consolas,"Liberation Mono",monospace',lineHeight:'1.85'},'.cm-content':{padding:'15px 0',caretColor:'#d3f76a'},'.cm-line':{padding:'0 12px 0 6px'},'.cm-gutters':{backgroundColor:'#1b1d20',color:'#62676c',border:'none',paddingRight:'8px',minWidth:'43px'},'.cm-activeLineGutter':{backgroundColor:'transparent',color:'#b3b9bf'},'.cm-activeLine':{backgroundColor:'#ffffff03'},'.cm-selectionBackground, &.cm-focused .cm-selectionBackground':{backgroundColor:'#47513770'},'&.cm-focused':{outline:'none'},'.cm-cursor':{borderLeftColor:'#d3f76a'}},{dark:true});
const highlighting=HighlightStyle.define([{tag:tags.keyword,color:'#c1a7e5'},{tag:tags.typeName,color:'#c1a7e5'},{tag:tags.comment,color:'#6c787e',fontStyle:'italic'},{tag:tags.string,color:'#b8d98a'},{tag:tags.number,color:'#deb986'},{tag:tags.bool,color:'#deb986'},{tag:tags.function(tags.variableName),color:'#8fc8d8'},{tag:tags.operator,color:'#adb6c3'}]);
const editor=new EditorView({state:EditorState.create({doc:project.code,extensions:[lineNumbers(),history(),drawSelection(),highlightActiveLine(),highlightActiveLineGutter(),cpp(),bracketMatching(),indentOnInput(),syntaxHighlighting(highlighting),theme,keymap.of([indentWithTab,...defaultKeymap,...historyKeymap]),EditorView.updateListener.of(u=>{if(u.docChanged){project.code=u.state.doc.toString();hexFile=null;saveSoon();}const line=u.state.doc.lineAt(u.state.selection.main.head);$('#cursor').textContent=`Стр ${line.number}, стлб ${u.state.selection.main.head-line.from+1}`;})]}),parent:$('#editor')});

function refreshIcons(){createIcons({icons,attrs:{'stroke-width':1.65}});}
function toast(title,detail='',kind='success'){
 const el=document.createElement('div');el.className=`toast ${kind}`;el.innerHTML=`<span class="toast-icon">${icon(kind==='error'?'circle-alert':kind==='info'?'info':'check')}</span><div><strong>${esc(title)}</strong>${detail?`<p>${esc(detail)}</p>`:''}</div><button class="icon-btn" aria-label="Закрыть">${icon('x')}</button>`;$('#toasts').append(el);el.querySelector('button').onclick=()=>el.remove();refreshIcons();setTimeout(()=>el.remove(),kind==='error'?9000:4200);
}
function audio(){if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();return audioContext;}
function chime(){if(!sound)return;try{const ctx=audio();[523.25,659.25,783.99].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.085;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.055,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+.24);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+.25);});}catch{}}
function setBuzz(id,f){if(!sound||!running||paused||f<20||f>20000){if(buzzers[id]){buzzers[id].stop();delete buzzers[id];}return;}try{const ctx=audio();if(!buzzers[id]){const o=ctx.createOscillator(),g=ctx.createGain();g.gain.value=.018;o.type='square';o.connect(g).connect(ctx.destination);o.start();buzzers[id]=o;}buzzers[id].frequency.value=f;}catch{}}
function silent(){for(const id in buzzers)setBuzz(id,0);}
function checkpoint(){undos.push(JSON.stringify({parts:project.parts,wires:project.wires}));if(undos.length>50)undos.shift();redos=[];}
function saveSoon(){clearTimeout(autosaveTimer);$('#saved').textContent='Сохраняем…';autosaveTimer=setTimeout(()=>{try{localStorage.setItem('volt.current',JSON.stringify(project));$('#saved').textContent='Сохранено на устройстве';}catch{$('#saved').textContent='Не удалось сохранить';}},450);}
window.addEventListener('pagehide',()=>{try{localStorage.setItem('volt.current',JSON.stringify(project));}catch{}});
function refreshMeta(){$('#project-name').innerHTML=`${esc(project.name)} ${icon('chevron-down')}`;$('.canvas-caption h1').textContent=project.name;$('.canvas-caption p').textContent=examples.find(ex=>ex.code===project.code)?.desc||'Arduino Uno · ваша схема';$('#part-count').textContent=project.parts.length;$('#wire-count').textContent=`Соединений: ${project.wires.length}`;refreshIcons();}
function renderCatalog(){
 const list=catalog.filter(p=>(!supportedOnly||p.ready)&&(group==='Все'||p.group===group)&&`${p.name} ${p.desc} ${p.tag}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(catalogOrder.includes(a.id)?catalogOrder.indexOf(a.id):100)-(catalogOrder.includes(b.id)?catalogOrder.indexOf(b.id):100));
 $('#catalog-count').textContent=catalog.length;$('#list-label').textContent=supportedOnly?'ДЛЯ ВАШЕЙ СХЕМЫ':'ВЕСЬ КАТАЛОГ';$('#ready-count').textContent=`${list.length} шт.`;
 $('[data-action="filter"]').setAttribute('aria-pressed',String(supportedOnly));$('[data-action="filter"]').setAttribute('title',supportedOnly?'Показать весь каталог':'Показать только доступные');
 $('#component-list').innerHTML=list.length?list.map(p=>`<button class="component-card ${p.ready?'':'unavailable'}" data-part="${p.id}" data-group="${esc(p.group)}" ${p.ready?'':'disabled aria-disabled="true"'} title="${esc(p.name+' · '+p.desc)}${p.ready?'':' · В разработке'}"><div class="component-art ${p.tag?'':'symbol-art'}" aria-hidden="true">${p.tag?`<wokwi-${p.tag}${p.id==='led'?' color="red"':p.id==='resistor'?' value="220"':''}></wokwi-${p.tag}>`:icon(catalogIcons[p.id]||(p.group==='Платы'?'cpu':p.group==='Дисплеи'?'monitor':'component'))}</div><strong>${esc(p.name)}</strong><span class="${p.ready?'component-category':'development-badge'}">${p.ready?(p.id==='uno'?'Плата Uno':p.group):'В разработке'}</span><span class="card-add">${icon(p.ready?'plus':'construction')}</span></button>`).join(''):`<div class="search-empty">Ничего не найдено.<br><small>Попробуйте другое название.</small></div>`;
 refreshIcons();fitCatalog();
}
function fitCatalog(){$$('.component-art').forEach(async holder=>{const el=holder.firstElementChild;if(!el?.tagName.startsWith('WOKWI-'))return;await el.updateComplete;el.style.transform='none';const w=el.offsetWidth,h=el.offsetHeight;if(!w||!h)return;el.style.transform=`scale(${Math.min(82/w,48/h,1.2)})`;el.setAttribute('aria-hidden','true');el.setAttribute('inert','');});}
const deviceScale=p=>p.type==='uno'?1.08:p.type==='led'||p.type==='rgb'?1.8:p.type==='resistor'?1.2:1;
const elements=new Map();
async function renderParts(){
 const host=$('#parts');host.innerHTML='';elements.clear();
 for(const part of project.parts){const meta=byId[part.type],scale=deviceScale(part),wrapper=document.createElement('div');wrapper.className='part';wrapper.dataset.id=part.id;wrapper.style.left=part.x+'px';wrapper.style.top=part.y+'px';wrapper.innerHTML=`<div class="part-label">${esc(part.type==='uno'?'ARDUINO UNO':part.id.toUpperCase())}</div><div class="device" style="transform:scale(${scale})"><wokwi-${meta.tag}></wokwi-${meta.tag}></div><div class="pins"></div>`;host.append(wrapper);const el=wrapper.querySelector(`wokwi-${meta.tag}`);elements.set(part.id,el);for(const[k,v]of Object.entries(part.attrs||{}))if(['color','value','horn','hornColor','label'].includes(k))el[k]=v;
  await el.updateComplete;wrapper.style.width=el.getBoundingClientRect().width/zoom+'px';wrapper.style.height=el.getBoundingClientRect().height/zoom+'px';
  wrapper.querySelector('.pins').innerHTML=(el.pinInfo||[]).map(pin=>`<button class="pin" style="left:${pin.x*scale}px;top:${pin.y*scale}px" data-pin="${part.id}:${esc(pin.name)}" title="${esc(part.id+' · '+pin.name)}" aria-label="Вывод ${esc(part.id+' '+pin.name)}"></button>`).join('');
  if(['button','button6'].includes(part.type)){el.addEventListener('button-press',()=>input(part.id,1));el.addEventListener('button-release',()=>input(part.id,0));}
  if(['pot','slidepot','switch'].includes(part.type))el.addEventListener('input',()=>{part.attrs.value=el.value;input(part.id,el.value);saveSoon();});
  if(part.type==='uno')el.addEventListener('button-press',()=>{if(running){stop();run();}});
 }
 drawWires();refreshMeta();selectPart(selected);$('#world').classList.toggle('wire-mode',mode==='wire');
}
function input(id,value){inputs[id]=value;worker?.postMessage({type:'input',id,value});}
function point(endpoint){const[id,name]=endpoint.split(':'),part=project.parts.find(p=>p.id===id),el=elements.get(id),pin=el?.pinInfo?.find(p=>p.name===name);if(!part||!pin)return null;return{x:part.x+pin.x*deviceScale(part),y:part.y+pin.y*deviceScale(part),partId:id};}
function routingBoxes(){return project.parts.map(p=>{const el=elements.get(p.id)?.closest('.part');return{id:p.id,x:p.x,y:p.y,w:parseFloat(el?.style.width)||40,h:parseFloat(el?.style.height)||40};});}
function pathBetween(a,b,boxes=routingBoxes()){return pointsToPath(routeWire(a,b,boxes));}
function drawWires(){
 const boxes=routingBoxes();$('#wires').innerHTML=project.wires.map(w=>{const a=point(w.from),b=point(w.to);if(!a||!b)return'';const path=pathBetween(a,b,boxes),fallback=`M ${a.x} ${a.y} L ${b.x} ${b.y}`;return`<g data-wire="${esc(w.id)}" class="${path?'':'route-blocked'}"><title>Нажмите, чтобы изменить провод</title><path class="wire-hit" d="${path||fallback}"/><path class="wire-line" stroke="${w.color}" d="${path||fallback}"/><circle cx="${a.x}" cy="${a.y}" r="3" fill="${w.color}"/><circle cx="${b.x}" cy="${b.y}" r="3" fill="${w.color}"/></g>`;}).join('')+'<path id="draft-wire"/>';if(wireStart&&draftCursor)renderDraft(draftCursor);
}
function worldPoint(e){const r=$('#canvas').getBoundingClientRect();return{x:Math.round((e.clientX-r.left-offset.x)/zoom),y:Math.round((e.clientY-r.top-offset.y)/zoom)};}
function wireHint(){$('#canvas-hint').textContent=wireStart?'Выберите конечный вывод · маршрут построится автоматически · Esc — отмена':'Нажмите на два вывода — провод сам обойдёт компоненты';}
function renderDraft(end){if(!wireStart||!end)return;draftCursor=end;const path=pathBetween(point(wireStart),end);$('#draft-wire')?.setAttribute('d',path);$('#draft-wire')?.setAttribute('stroke',wireColor);}
function setTransform(){$('#world').style.transform=`translate(${offset.x}px,${offset.y}px) scale(${zoom})`;$('#zoom-label').textContent=Math.round(zoom*100)+'%';}
function fit(){const rect=$('#canvas').getBoundingClientRect();if(rect.width<1||rect.height<1)return;const boxes=project.parts.map(p=>{const el=$$('.part').find(e=>e.dataset.id===p.id);return{x:p.x,y:p.y,w:parseFloat(el?.style.width)||100,h:parseFloat(el?.style.height)||100};});if(!boxes.length){zoom=1;offset={x:0,y:0};setTransform();return;}const minX=Math.min(...boxes.map(p=>p.x))-15,minY=Math.min(...boxes.map(p=>p.y))-40,maxX=Math.max(...boxes.map(p=>p.x+p.w))+15,maxY=Math.max(...boxes.map(p=>p.y+p.h))+15,bw=maxX-minX,bh=maxY-minY;zoom=Math.max(.3,Math.min(1.4,(rect.width-60)/bw,(rect.height-190)/bh));offset={x:(rect.width-bw*zoom)/2-minX*zoom,y:110+(rect.height-190-bh*zoom)/2-minY*zoom};setTransform();}
function selectPart(id){selected=project.parts.some(p=>p.id===id)?id:null;$$('.part').forEach(el=>el.classList.toggle('selected',el.dataset.id===selected));const panel=$('#inspector');if(!selected){panel.hidden=true;return;}const p=project.parts.find(p=>p.id===selected);panel.hidden=false;panel.innerHTML=`<div><strong>${esc(byId[p.type].name)}</strong><small>${esc(p.id)}${p.type==='resistor'?` · ${esc(p.attrs.value||220)} Ω`:''}</small></div>${p.type==='led'?`<input type="color" id="led-color" value="${/^#[\da-f]{6}$/i.test(p.attrs.color)?p.attrs.color:'#ff4444'}" aria-label="Цвет светодиода">`:''}${p.type==='resistor'?`<label class="resistance"><input id="resistance" type="number" min="1" max="10000000" value="${Number(p.attrs.value)||220}" aria-label="Сопротивление">Ω</label>`:''}<span class="inspector-actions">${btn('move','move-hint','Перемещение стрелками')}${btn('trash-2','delete','Удалить компонент')}${btn('x','deselect','Закрыть свойства')}</span>`;refreshIcons();$('#led-color')?.addEventListener('input',e=>{p.attrs.color=e.target.value;elements.get(p.id).color=e.target.value;saveSoon();});$('#resistance')?.addEventListener('change',e=>{if(running)return;checkpoint();p.attrs.value=String(Math.max(1,Math.min(10000000,Number(e.target.value)||220)));elements.get(p.id).value=p.attrs.value;saveSoon();});}
function editAllowed(){if(running||compiling){toast('Сначала остановите симуляцию','После остановки можно изменить схему.','info');return false;}return true;}
function addPart(type){if(!editAllowed())return;const p=byId[type];if(!p.ready){toast('Эта модель в разработке',p.name+' есть в каталоге, но ещё не моделируется.','info');return;}if(type==='uno'&&project.parts.some(p=>p.type==='uno'))return toast('Uno уже на схеме','В этой версии поддерживается одна плата.','info');checkpoint();const rect=$('#canvas').getBoundingClientRect();const id=type+'-'+uid();project.parts.push({id,type,x:Math.max(30,(rect.width*.6-offset.x)/zoom),y:Math.max(130,(rect.height*.55-offset.y)/zoom),attrs:type==='led'?{color:'red'}:type==='resistor'?{value:'220'}:{}});selected=id;renderParts();saveSoon();$('.palette').classList.remove('open');}
function connect(endpoint){if(!editAllowed())return;if(!wireStart){selectPart(null);wireStart=endpoint;draftCursor=point(endpoint);$$('.pin').find(p=>p.dataset.pin===endpoint)?.classList.add('pending');$('#world').classList.add('drawing-wire');wireHint();return;}if(wireStart!==endpoint&&!project.wires.some(w=>(w.from===wireStart&&w.to===endpoint)||(w.to===wireStart&&w.from===endpoint))){checkpoint();project.wires.push({id:uid(),from:wireStart,to:endpoint,color:wireColor});saveSoon();}cancelWire();drawWires();refreshMeta();}
function cancelWire(){wireStart=null;draftCursor=null;$$('.pin.pending').forEach(p=>p.classList.remove('pending'));$('#world').classList.remove('drawing-wire');$('#draft-wire')?.setAttribute('d','');wireHint();}
$('#canvas').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.pin')){e.preventDefault();e.stopPropagation();connect(e.target.dataset.pin);}});

let drag=null;
$('#canvas').addEventListener('pointerdown',e=>{
 if(e.target.closest('#inspector,.canvas-bottom'))return;
 const pin=e.target.closest('[data-pin]');if(pin){e.preventDefault();connect(pin.dataset.pin);return;}
 if(wireStart){e.preventDefault();return;}
 const w=e.target.closest('[data-wire]');if(w){if(editAllowed()){const id=w.dataset.wire;openDialog('Соединение',`<p class="dialog-text">${esc(project.wires.find(w=>w.id===id).from)} → ${esc(project.wires.find(w=>w.id===id).to)}</p><button class="button danger" id="remove-wire">${icon('trash-2')}Удалить провод</button>`);$('#remove-wire').onclick=()=>{checkpoint();project.wires=project.wires.filter(w=>w.id!==id);drawWires();refreshMeta();saveSoon();closeDialog();};}return;}
 if(e.target.closest('#inspector,.canvas-bottom'))return;
 const wrapper=e.target.closest('.part');if(wrapper){selectPart(wrapper.dataset.id);if(running)return;if(wireStart)return;const p=project.parts.find(p=>p.id===wrapper.dataset.id);checkpoint();drag={id:p.id,startX:e.clientX,startY:e.clientY,x:p.x,y:p.y};wrapper.setPointerCapture(e.pointerId);e.preventDefault();}
 else{selectPart(null);if(!e.target.closest('button')){drag={pan:true,startX:e.clientX,startY:e.clientY,x:offset.x,y:offset.y};$('#canvas').setPointerCapture(e.pointerId);}}
});
$('#canvas').addEventListener('pointermove',e=>{
 if(drag){if(drag.pan){offset={x:drag.x+e.clientX-drag.startX,y:drag.y+e.clientY-drag.startY};setTransform();}else{const p=project.parts.find(p=>p.id===drag.id);p.x=Math.max(0,Math.min(1800,drag.x+(e.clientX-drag.startX)/zoom));p.y=Math.max(0,Math.min(1200,drag.y+(e.clientY-drag.startY)/zoom));const el=$$('.part').find(el=>el.dataset.id===p.id);el.style.left=p.x+'px';el.style.top=p.y+'px';drawWires();}}
 if(wireStart){const target=e.target.closest('[data-pin]');renderDraft(target?point(target.dataset.pin):worldPoint(e));}
});
$('#canvas').addEventListener('pointerup',()=>{if(drag&&!drag.pan)saveSoon();drag=null;});
$('#canvas').addEventListener('pointercancel',()=>{drag=null;});
$('#canvas').addEventListener('wheel',e=>{e.preventDefault();const rect=$('#canvas').getBoundingClientRect(),old=zoom;zoom=Math.max(.3,Math.min(2.5,zoom*(e.deltaY>0?.92:1.08)));offset.x=e.clientX-rect.left-(e.clientX-rect.left-offset.x)*zoom/old;offset.y=e.clientY-rect.top-(e.clientY-rect.top-offset.y)*zoom/old;setTransform();},{passive:false});

let logCount=0,serialLines=0;
function appendLog(text,kind='info'){const row=document.createElement('div');row.className=`log-line ${kind}`;row.textContent=text;$('#build-output').append(row);$('#build-output').scrollTop=$('#build-output').scrollHeight;$('#log-count').textContent=++logCount;while($('#build-output').children.length>200)$('#build-output').firstChild.remove();}
function appendSerial(text){if(!serialLines)$('#serial-output').innerHTML='';serialLines++;const row=document.createElement('div');row.className='serial-line';const time=document.createElement('span');time.className='serial-time';time.textContent=seconds.toFixed(3).padStart(7,'0');const content=document.createElement('span');content.textContent=text;row.append(time,content);$('#serial-output').append(row);while($('#serial-output').children.length>400)$('#serial-output').firstChild.remove();$('#serial-output').scrollTop=$('#serial-output').scrollHeight;}
function consolePanel(panel){activePanel=panel;$('#serial-output').hidden=panel!=='serial';$('#build-output').hidden=panel!=='logs';$('[data-action="serial-panel"]').classList.toggle('active',panel==='serial');$('[data-action="logs-panel"]').classList.toggle('active',panel==='logs');}
async function run(){
 if(running){stop();return;}if(compiling)return;cancelWire();dismissError();
 const generation=++runGeneration,sourceCode=project.code;
 try{
  const warnings=validateCircuit(project);for(const warning of warnings)appendLog('△ '+warning,'warning');
  compiling=true;$('#run').innerHTML=`${icon('loader-circle','spin')}<span>Собираем…</span>`;$('#run').disabled=true;$('#canvas-status').textContent='Компиляция скетча…';refreshIcons();if(sound)audio();
  let result;if(hexFile){result={hex:hexFile,stdout:'Загружена прошивка Intel HEX. Содержимое редактора не компилировалось.'};}
  else if(compiler){const response=await fetch('/api/compile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:project.code}),signal:AbortSignal.timeout(65000)});result=await response.json();if(!response.ok||!result.hex)throw Error(result.error||'Компилятор не вернул прошивку.');}
  else{const sample=examples.find(ex=>ex.code===project.code);if(!sample){throw Error('Веб-версия запускает готовые примеры и файлы .hex. Для сборки изменённого C++ откройте локальный SIMduino lab на компьютере с Arduino CLI. Ваш код сохранён.');}result=(await firmware)[sample.id];if(!result?.hex)throw Error('Не удалось загрузить готовую прошивку.');}
  if(generation!==runGeneration)return;if(project.code!==sourceCode)throw Error('Код изменился во время сборки. Нажмите «Запустить» ещё раз.');
  loadHex(result.hex);appendLog(hexFile?'Запуск загруженной прошивки.':compiler?'Сборка завершена · Arduino Uno':'Загружена готовая прошивка примера.','success');if(result.stdout)appendLog(result.stdout.trim());
  seconds=0;serialLines=0;$('#serial-output').innerHTML='';worker=new Worker('/simulator.js',{type:'module'});worker.onmessage=({data})=>{
   if(data.type==='ready'){running=true;paused=false;setRunUI();chime();launchFireworks();showSuccessReaction();toast('Схема ожила','Arduino Uno выполняет вашу прошивку.');appendLog('Эмуляция ATmega328P запущена · 16 MHz','success');}
   if(data.type==='frame'){seconds=data.seconds;updateAmbient(data.outputs,project.parts);for(const [id,out]of Object.entries(data.outputs)){const el=elements.get(id);if(!el)continue;if('brightness'in out){el.value=out.brightness>.005;el.brightness=out.brightness;el.style.filter=out.brightness>.05?`drop-shadow(0 0 ${10*out.brightness}px ${project.parts.find(p=>p.id===id).attrs.color||'red'})`:'';}if(out.rgb){[el.ledRed,el.ledGreen,el.ledBlue]=out.rgb;}if('angle'in out)el.angle=out.angle;if('frequency'in out)setBuzz(id,out.frequency);}
    const uno=elements.get(project.parts.find(p=>p.type==='uno').id);if(uno){uno.ledPower=true;uno.led13=data.pins[13]>.1;}$('#simulation-time').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${(seconds%60).toFixed(3).padStart(6,'0')}`;
   }if(data.type==='serial')appendSerial(data.line);if(data.type==='error'){stop();showError(data.message);}
  };worker.onerror=e=>{stop();showError(e.message||'Ошибка эмулятора.');};worker.postMessage({type:'start',hex:result.hex,project:structuredClone(project),inputs});
 }catch(e){showError(e.message);$('#canvas-status').textContent='Исправьте ошибку';}
 finally{if(generation===runGeneration){compiling=false;$('#run').disabled=false;if(!running)setRunUI();}}
}
function setRunUI(){
 $('#run').innerHTML=running?`${icon('square')}<span>Остановить</span><kbd>⌘ ↵</kbd>`:`${icon('play')}<span>Запустить</span><kbd>⌘ ↵</kbd>`;$('#run').classList.toggle('running',running);$('#run-dot').classList.toggle('live',running&&!paused);$('#canvas-status').textContent=running?(paused?'На паузе':'Симуляция работает'):'Готово к запуску';$('#world').classList.toggle('simulating',running);$('#bottom-status').textContent=running?'Эмуляция в браузере':'Локальное сохранение';$('.canvas-caption').classList.toggle('dim',running);refreshIcons();
}
function stop(){runGeneration++;worker?.terminate();worker=null;running=false;paused=false;compiling=false;$('#run').disabled=false;clearAmbient();silent();elements.forEach(el=>{if('value'in el&&el.tagName==='WOKWI-LED'){el.value=false;el.brightness=0;el.style.filter='';}if('ledRed'in el){el.ledRed=0;el.ledGreen=0;el.ledBlue=0;}if('ledPower'in el)el.ledPower=false;if('led13'in el)el.led13=false;});setRunUI();}
function showError(message){appendLog(message,'error');consolePanel('logs');showCompileError(message);showFailureReaction();toast('Не удалось запустить',message.split('\n').find(s=>s.includes('error:'))||message.slice(0,200),'error');}
function openDialog(title,content,wide=false){const d=$('#modal');d.className=wide?'wide':'';d.innerHTML=`<div class="dialog-header"><h2>${esc(title)}</h2>${btn('x','close','Закрыть')}</div><div class="dialog-body">${content}</div>`;if(!d.open)d.showModal();refreshIcons();}
function closeDialog(){$('#modal').close();}
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
function rememberProject(){try{const stored=JSON.parse(localStorage.getItem('volt.projects')||'[]'),i=stored.findIndex(x=>x.name===project.name),entry={...structuredClone(project),updated:Date.now()};if(i>=0)stored[i]=entry;else stored.unshift(entry);localStorage.setItem('volt.projects',JSON.stringify(stored.slice(0,30)));}catch{}}
function chooseExample(id){const ex=examples.find(x=>x.id===id);if(!ex)return;rememberProject();stop();project=makeProject(ex);hexFile=null;selected=null;undos=[];redos=[];inputs={};editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:project.code}});renderParts().then(fit);saveSoon();closeDialog();toast('Открыт пример',ex.name,'info');}
function exportFile(filename,text,type='application/json'){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function saveProject(){try{localStorage.setItem('volt.current',JSON.stringify(project));const stored=JSON.parse(localStorage.getItem('volt.projects')||'[]');const name=project.name;const entry={...structuredClone(project),updated:Date.now()};const i=stored.findIndex(x=>x.name===name);if(i>=0)stored[i]=entry;else stored.unshift(entry);localStorage.setItem('volt.projects',JSON.stringify(stored.slice(0,30)));exportFile(project.name.replace(/[^\p{L}\p{N} _-]/gu,'')+'.simduino.json',JSON.stringify(project,null,2));toast('Проект сохранён','Файл со схемой и кодом можно отправить одногруппникам.');}catch(e){toast('Не удалось сохранить',e.message,'error');}}
const actions={
 run,close:closeDialog,save:saveProject,workspace:()=>closeDialog(),
 sound:()=>{sound=!sound;localStorage.setItem('volt.sound',sound?'on':'off');if(!sound)silent();else chime();updateSound();toast(sound?'Звук включён':'Звук выключен','','info');},
 palette:()=>{$('.palette').classList.toggle('open');fitCatalog();},
 filter:()=>{supportedOnly=!supportedOnly;renderCatalog();},
 catalog:()=>{supportedOnly=false;search='';group='Все';$('#search').value='';$('#category').value='Все';renderCatalog();toast('Весь каталог','Доступны 11 моделей. Остальные помечены «В разработке».','info');},
 fit, 'zoom-in':()=>{zoom=Math.min(2.5,zoom+.1);setTransform();},'zoom-out':()=>{zoom=Math.max(.3,zoom-.1);setTransform();},
 select:()=>{mode='select';$('#world').classList.remove('wire-mode');$('[data-action="select"]').classList.add('active');$('[data-action="wire"]').classList.remove('active');cancelWire();},
 wire:()=>{mode='wire';$('#world').classList.add('wire-mode');$('[data-action="select"]').classList.remove('active');$('[data-action="wire"]').classList.add('active');},
 deselect:()=>selectPart(null), 'move-hint':()=>toast('Перемещение','Перетащите деталь или используйте стрелки. Shift + стрелка — шаг 10.','info'),
 delete:()=>{if(!selected||!editAllowed())return;checkpoint();project.parts=project.parts.filter(p=>p.id!==selected);project.wires=project.wires.filter(w=>!w.from.startsWith(selected+':')&&!w.to.startsWith(selected+':'));selected=null;renderParts();saveSoon();},
 undo:()=>{if(!editAllowed()||!undos.length)return;redos.push(JSON.stringify({parts:project.parts,wires:project.wires}));Object.assign(project,JSON.parse(undos.pop()));renderParts();saveSoon();},
 redo:()=>{if(!editAllowed()||!redos.length)return;undos.push(JSON.stringify({parts:project.parts,wires:project.wires}));Object.assign(project,JSON.parse(redos.pop()));renderParts();saveSoon();},
 copy:async()=>{try{await navigator.clipboard.writeText(project.code);toast('Код скопирован');}catch{exportFile('sketch.ino',project.code,'text/plain');}},
 import:()=>$('#file-input').click(),hex:()=>$('#hex-input').click(),
 'serial-panel':()=>consolePanel('serial'),'logs-panel':()=>consolePanel('logs'),
 'clear-console':()=>{if(activePanel==='serial'){$('#serial-output').innerHTML='';serialLines=0;}else{$('#build-output').innerHTML='';logCount=0;$('#log-count').textContent='0';}},
 rename:()=>{openDialog('Название проекта',`<form id="rename-form"><label class="field-label" for="rename-input">Как назовём эту схему?</label><input class="text-input" id="rename-input" value="${esc(project.name)}" maxlength="100" required><button class="button primary">Сохранить название</button></form>`);$('#rename-form').onsubmit=e=>{e.preventDefault();project.name=$('#rename-input').value.trim()||'Новый проект';refreshMeta();saveSoon();closeDialog();};},
 examples:()=>{openDialog('Идеи для первой искры',`<p class="dialog-text">Готовые схемы с настоящими прошивками Uno. Текущая работа сохранена на устройстве; чтобы оставить отдельную копию, нажмите «Сохранить».</p><div class="example-grid">${examples.map((ex,i)=>`<button class="example-card" data-example="${ex.id}"><span class="example-top">${icon(ex.icon)}<span>0${i+1}</span></span><span class="pill">${ex.level}</span><strong>${ex.name}</strong><p>${ex.desc}</p><span class="example-open">Открыть схему ${icon('arrow-up-right')}</span></button>`).join('')}</div>`,true);},
 projects:()=>{let stored=[];try{stored=JSON.parse(localStorage.getItem('volt.projects')||'[]');}catch{}openDialog('Мои проекты',`<p class="dialog-text">Проекты хранятся в этом браузере. Скачивайте файл, чтобы перенести работу на другой компьютер.</p><div class="project-list">${stored.length?stored.map((p,i)=>`<button data-project-index="${i}">${icon('folder')}<span><strong>${esc(p.name)}</strong><small>${new Date(p.updated).toLocaleDateString('ru-RU')} · ${p.parts.length} компонентов</small></span>${icon('arrow-up-right')}</button>`).join(''):`<div class="empty-projects">${icon('folder-open')}<h3>Место для ваших открытий</h3><p>Нажмите «Сохранить» в рабочей области.<br>Ваш первый проект появится здесь.</p></div>`}</div><button class="button secondary" data-action="import">${icon('folder-input')}Открыть файл проекта</button>`);$$('[data-project-index]').forEach(b=>b.onclick=()=>{try{const p=stored[Number(b.dataset.projectIndex)];validateProject(p);stop();project=structuredClone(p);selected=null;hexFile=null;editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:project.code}});renderParts().then(fit);saveSoon();closeDialog();}catch(e){toast('Не удалось открыть',e.message,'error');}});},
 help:()=>openDialog('Ваша маленькая лаборатория',`<div class="help-list"><div><b>01</b><span><strong>Соберите схему</strong><p>Нажмите на деталь в каталоге. Перетащите её на свободное место. Нажмите на первый вывод, затем на второй — провод автоматически обойдёт компоненты.</p></span></div><div><b>02</b><span><strong>Напишите код</strong><p>Редактор справа понимает Arduino C++. Нажмите «Запустить» или ⌘/Ctrl + Enter. Проверяйте Serial в мониторе порта.</p></span></div><div><b>03</b><span><strong>Экспериментируйте</strong><p>Во время запуска можно нажимать кнопки и вращать потенциометр. Остановите симуляцию, чтобы изменить соединения.</p></span></div></div><div class="info-box">${compiler?'Собственный компилятор подключён: можно запускать изменённый код.':'Это веб-версия: запускаются 7 готовых примеров и импортированные .hex. Сборка изменённого C++ доступна в локальной версии с Arduino CLI.'}</div><p class="dialog-text small">Колесо — масштаб · фон — перемещение · Delete — удалить · Esc — отменить провод. Файлы сохраняются на ваше устройство.</p>`),
 about:()=>openDialog('SIMduino lab · Открытая лаборатория',`<div class="about-mark"><img src="/favicon.svg" class="s-mark" alt=""></div><h3>Место, где идеи оживают.</h3><p class="dialog-text">Версия 0.1 для Arduino Uno. Настоящее выполнение AVR-прошивки в браузере, собственная компиляция Arduino CLI в локальной версии.</p><div class="support-facts"><span><b>11</b> моделей</span><span><b>7</b> примеров</span><span><b>0</b> подписок</span></div><p class="dialog-text">Сейчас работают Uno, светодиод, RGB, резистор, две кнопки, переключатель, два потенциометра, сервопривод и пьезодинамик. Аналоговая электрическая модель, остальные платы, датчики, дисплеи и протоколы пока не реализованы.</p><p class="dialog-text small">Открытые библиотеки: <a href="https://github.com/wokwi/avr8js" target="_blank" rel="noreferrer">AVR8js</a>, <a href="https://github.com/wokwi/wokwi-elements" target="_blank" rel="noreferrer">Wokwi Elements</a> (MIT). Независимый проект, не сервис Wokwi. <a href="/THIRD-PARTY-LICENSES.txt" target="_blank">Лицензии</a>.</p>`),
 'view-circuit':()=>{document.body.classList.remove('code-view');$('[data-action="view-circuit"]').classList.add('active');$('[data-action="view-code"]').classList.remove('active');setTimeout(fit,20);},
 'view-code':()=>{document.body.classList.add('code-view');$('[data-action="view-code"]').classList.add('active');$('[data-action="view-circuit"]').classList.remove('active');editor.requestMeasure();}
};
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action)actions[action.dataset.action]?.();const part=e.target.closest('[data-part]');if(part)addPart(part.dataset.part);const ex=e.target.closest('[data-example]');if(ex)chooseExample(ex.dataset.example);});
function updateSound(){const b=$('[data-action="sound"]');b.innerHTML=icon(sound?'volume-2':'volume-x');b.setAttribute('aria-pressed',String(sound));b.title=sound?'Выключить звук':'Включить звук';refreshIcons();}
$('#search').oninput=e=>{search=e.target.value;renderCatalog();};$('#category').onchange=e=>{group=e.target.value;renderCatalog();};$('#wire-color').oninput=e=>wireColor=e.target.value;
$('#serial-form').onsubmit=e=>{e.preventDefault();const text=$('#serial-input').value;if(!running){toast('Сначала запустите плату','','info');return;}if(text){worker.postMessage({type:'serial',text:text+'\n'});appendSerial('→ '+text);$('#serial-input').value='';}};
$('#file-input').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>500000)throw Error('Проект должен быть меньше 500 КБ.');const imported=JSON.parse(await file.text());validateProject(imported);rememberProject();stop();project=imported;selected=null;hexFile=null;undos=[];redos=[];inputs={};editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:project.code}});await renderParts();fit();saveSoon();closeDialog();toast('Проект открыт',file.name);}catch(e){toast('Ошибка открытия',e.message,'error');}finally{$('#file-input').value='';}};
$('#hex-input').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>200000)throw Error('Файл HEX слишком большой.');const data=await file.text();loadHex(data);stop();hexFile=data;$('#compiler-label').textContent='Прошивка HEX';toast('Прошивка загружена','При запуске будет выполнен HEX, а не код редактора.','info');}catch(e){toast('Ошибка прошивки',e.message,'error');}finally{$('#hex-input').value='';}};
document.addEventListener('keydown',e=>{const editing=e.composedPath().some(el=>el.tagName==='INPUT'||el.tagName==='TEXTAREA'||el.isContentEditable);if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run();}if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();saveProject();}if(e.key==='Escape'){cancelWire();selectPart(null);}if($('#modal').open||editing)return;if(e.key==='/'){e.preventDefault();$('#search').focus();}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();actions.delete();}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?actions.redo():actions.undo();}if(selected&&e.key.startsWith('Arrow')&&!running){e.preventDefault();checkpoint();const p=project.parts.find(p=>p.id===selected),d=e.shiftKey?10:2;p.x+=e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0;p.y+=e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0;renderParts();saveSoon();}});
mountAmbient();preloadReactions();renderCatalog();await renderParts();fit();updateSound();refreshIcons();
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{fit();fitCatalog();editor.requestMeasure();},150);});
try{const r=await fetch('/api/health',{signal:AbortSignal.timeout(2500)});if(r.ok)compiler=!!(await r.json()).compiler;}catch{}
$('#compiler-label').innerHTML=compiler?'<span class="compiler-dot"></span>Компилятор подключён':'Готовые примеры + HEX';
appendLog(compiler?'Локальный компилятор Arduino Uno готов.':'Веб-режим: готовые примеры и загрузка HEX. Изменённый C++ собирается в локальной версии.');
