const item = (id,name,group,tag,desc,ready=false) => ({id,name,group,tag,desc,ready});
export const catalog = [
 item('uno','Arduino Uno','Платы','arduino-uno','ATmega328P · 16 MHz',true),
 item('led','Светодиод','Свет','led','5 мм · любой цвет',true),
 item('resistor','Резистор','Базовые','resistor','Ограничение тока',true),
 item('button','Кнопка','Ввод','pushbutton','Нажмите в симуляции',true),
 item('pot','Потенциометр','Ввод','potentiometer','Аналоговый вход · 0–5 В',true),
 item('buzzer','Пьезодинамик','Звук и моторы','buzzer','tone() · звук в браузере',true),
 item('servo','Сервопривод','Звук и моторы','servo','PWM · 0–180°',true),
 item('rgb','RGB-светодиод','Свет','rgb-led','Три канала · общий катод',true),
 item('switch','Переключатель','Ввод','slide-switch','Два положения',true),
 item('button6','Кнопка 6 мм','Ввод','pushbutton-6mm','Моментальный контакт',true),
 item('slidepot','Слайдер','Ввод','slide-potentiometer','Аналоговый вход · 0–5 В',true),
 item('nano','Arduino Nano','Платы','arduino-nano','ATmega328P'),
 item('mega','Arduino Mega','Платы','arduino-mega','ATmega2560'),
 item('tiny','ATtiny85','Платы',null,'AVR · 8 бит'),
 ...['ESP32','ESP32-S2','ESP32-S3','ESP32-C3','ESP32-C5','ESP32-C6','ESP32-C61','ESP32-H2','ESP32-P4','ESP32-S31'].map(name=>item(name.toLowerCase(),name,'Платы',name==='ESP32'?'esp32-devkit-v1':null,'Xtensa / RISC-V')),
 ...['STM32C031','STM32L031','STM32F103C8','Raspberry Pi Pico'].map(name=>item(name.toLowerCase().replaceAll(' ','-'),name,'Платы',null,'ARM Cortex')),
 item('ultrasonic','HC-SR04','Датчики','hc-sr04','Ультразвуковой дальномер'),
 item('dht','DHT22','Датчики','dht22','Температура и влажность'),
 item('rtc','DS1307 RTC','Датчики','ds1307','Часы реального времени · I²C'),
 item('pir','PIR-датчик','Датчики','pir-motion-sensor','Датчик движения'),
 item('ntc','NTC-термистор','Датчики','ntc-temperature-sensor','Аналоговая температура'),
 item('ds18','DS18B20','Датчики',null,'Температура · OneWire'),
 item('bmp','BMP180','Датчики',null,'Давление · I²C'),
 item('mpu','MPU6050','Датчики','mpu6050','Акселерометр и гироскоп'),
 item('ldr','Фоторезистор','Датчики','photoresistor-sensor','Освещённость'),
 item('gas','MQ2','Датчики','gas-sensor','Датчик газа'),
 item('hx','HX711','Датчики','hx711','Тензодатчик'),
 item('rfid','MFRC522','Датчики',null,'RFID · SPI'),
 item('dip','DIP Switch 8','Ввод','dip-switch-8','8 переключателей'),
 item('keypad','Клавиатура 4×4','Ввод','membrane-keypad','Матричный ввод'),
 item('joystick','Джойстик','Ввод','analog-joystick','Две оси и кнопка'),
 item('encoder','KY-040','Ввод','ky-040','Поворотный энкодер'),
 item('bar','LED Bar Graph','Свет','led-bar-graph','10 сегментов'),
 item('pixel','WS2812','Свет','neopixel','Адресный светодиод'),
 item('ring','Кольцо WS2812','Свет','led-ring','NeoPixel Ring'),
 item('strip','Лента WS2812','Свет',null,'NeoPixel Strip'),
 item('matrix','Матрица WS2812','Свет','neopixel-matrix','NeoPixel Matrix'),
 item('meter','NeoPixel Meter','Свет',null,'Частота кадров и мощность'),
 item('nlsf','NLSF595','Логика',null,'Трёхцветный драйвер · SPI'),
 item('lcd','LCD 1602','Дисплеи','lcd1602','16 символов × 2 строки'),
 item('lcd20','LCD 2004','Дисплеи','lcd2004','20 символов × 4 строки'),
 item('nokia','Nokia 5110','Дисплеи',null,'84 × 48 · SPI'),
 item('tft','ILI9341','Дисплеи','ili9341','240 × 320 · цветной TFT'),
 item('touch','ILI9341 Touch','Дисплеи',null,'TFT + FT6206'),
 item('oled','SSD1306 OLED','Дисплеи','ssd1306','128 × 64 · I²C'),
 item('sh1107','SH1107 OLED','Дисплеи',null,'128 × 128 · I²C'),
 item('max7219','MAX7219','Дисплеи',null,'Светодиодная матрица 8×8'),
 item('seven','7-сегм. индикатор','Дисплеи','7segment','От 1 до 4 цифр'),
 item('tm1637','TM1637','Дисплеи',null,'4-разрядный индикатор'),
 item('epaper','e-Paper 2.9″','Дисплеи',null,'Электронная бумага'),
 item('pal','PAL TV','Дисплеи',null,'Чёрно-белый видеосигнал'),
 item('stepper','Шаговый двигатель','Звук и моторы','stepper-motor','Биполярный'),
 item('a4988','A4988','Звук и моторы',null,'Драйвер шагового двигателя'),
 item('biaxial','Двухосевой мотор','Звук и моторы','biaxial-stepper','Два шаговых двигателя'),
 item('ir','ИК-приёмник','Связь','ir-receiver','38 кГц'),
 item('remote','ИК-пульт','Связь','ir-remote','20 клавиш'),
 ...['NOT','AND','OR','XOR','NAND','MUX','Flip-Flop D','Flip-Flop DSR','74HC595','74HC165'].map(name=>item(name.toLowerCase().replaceAll(' ','-'),name,'Логика',null,'Цифровая логика')),
 item('clock','Генератор частоты','Базовые',null,'Тактовый сигнал'),
 item('relay','Модуль реле','Базовые',null,'Управляемый контакт'),
 item('dpdt','DPDT-реле','Базовые','ks2e-m-dc5','Два переключающих контакта'),
 item('breadboard','Макетная плата','Базовые',null,'Полная, половинная и мини'),
 item('analyzer','Логический анализатор','Базовые',null,'8 цифровых каналов'),
 item('sd','microSD','Связь','microsd-card','Карта памяти · SPI'),
 item('text','Подпись','Базовые',null,'Текст на схеме'),
];
export const byId = Object.fromEntries(catalog.map(p=>[p.id,p]));
export const groups = ['Все','Базовые','Платы','Свет','Ввод','Датчики','Дисплеи','Звук и моторы','Логика','Связь'];
