const uno = {id:'uno',type:'uno',x:125,y:155,attrs:{}};
const led = (id,x,y,color='red')=>({id,type:'led',x,y,attrs:{color}});
const resistor=(id,x,y)=>({id,type:'resistor',x,y,attrs:{value:'220'}});
const pinName=endpoint=>endpoint.split(':').slice(1).join(':').toUpperCase();
const wire=(from,to,color='#d8f65d')=>{const pins=[pinName(from),pinName(to)];return{id:`${from}-${to}`,from,to,color:pins.some(pin=>pin.includes('GND'))?'#111111':pins.some(pin=>pin==='5V'||pin==='VCC'||pin==='V+')?'#ef4f55':color};};
export const examples = [
 {id:'blink',name:'Первое мигание',desc:'Знакомство с digitalWrite() и delay().',level:'Начало',icon:'lightbulb',parts:[uno,led('led1',470,120),resistor('r1',450,250)],wires:[wire('uno:13','r1:1'),wire('r1:2','led1:A'),wire('led1:C','uno:GND.1','#829399')],code:`// Первое мигание\n// Светодиод → резистор 220 Ом → пин 13\n\nconst int LED = 13;\n\nvoid setup() {\n  pinMode(LED, OUTPUT);\n  Serial.begin(9600);\n  Serial.println("Hello, SIMduino lab!");\n}\n\nvoid loop() {\n  digitalWrite(LED, HIGH);\n  Serial.println("LED: ON");\n  delay(1000);\n\n  digitalWrite(LED, LOW);\n  Serial.println("LED: OFF");\n  delay(1000);\n}\n`},
 {id:'traffic',name:'Светофор',desc:'Три светодиода и последовательность сигналов.',level:'Начало',icon:'traffic-cone',parts:[uno,...['red','yellow','green'].flatMap((c,i)=>[led(`l${i}`,450+i*65,100,c),resistor(`r${i}`,440+i*65,230+i*35)])],wires:[0,1,2].flatMap(i=>[wire(`uno:${11-i}`,`r${i}:1`,['#ef7575','#eac965','#8adb9b'][i]),wire(`r${i}:2`,`l${i}:A`),wire(`l${i}:C`,'uno:GND.1','#829399')]),code:`// Светофор: красный 11, жёлтый 10, зелёный 9\nvoid setup() {\n  for (int pin = 9; pin <= 11; pin++) {\n    pinMode(pin, OUTPUT);\n  }\n}\n\nvoid loop() {\n  digitalWrite(11, HIGH);\n  delay(3000);\n  digitalWrite(10, HIGH);\n  delay(1000);\n  digitalWrite(11, LOW);\n  digitalWrite(10, LOW);\n  digitalWrite(9, HIGH);\n  delay(3000);\n  digitalWrite(9, LOW);\n  digitalWrite(10, HIGH);\n  delay(1000);\n  digitalWrite(10, LOW);\n}\n`},
 {id:'button',name:'Кнопка и свет',desc:'Управляйте светом. Вход с INPUT_PULLUP.',level:'Начало',icon:'mouse-pointer-2',parts:[uno,led('led1',480,120),resistor('r1',455,235),{id:'btn',type:'button',x:475,y:330,attrs:{color:'green'}}],wires:[wire('uno:13','r1:1'),wire('r1:2','led1:A'),wire('led1:C','uno:GND.1','#829399'),wire('btn:1.l','uno:2','#99a9ff'),wire('btn:2.l','uno:GND.2','#829399')],code:`// Нажмите кнопку на схеме во время запуска\nvoid setup() {\n  pinMode(13, OUTPUT);\n  pinMode(2, INPUT_PULLUP);\n  Serial.begin(9600);\n}\n\nvoid loop() {\n  bool pressed = digitalRead(2) == LOW;\n  digitalWrite(13, pressed ? HIGH : LOW);\n  Serial.println(pressed ? "PRESSED" : "RELEASED");\n  delay(100);\n}\n`},
 {id:'fade',name:'Плавный свет',desc:'Изменяйте яркость с помощью analogWrite().',level:'PWM',icon:'sun',parts:[uno,led('led1',480,120,'green'),resistor('r1',455,235)],wires:[wire('uno:9','r1:1'),wire('r1:2','led1:A'),wire('led1:C','uno:GND.1','#829399')],code:`// Плавное изменение яркости · PWM на пине 9\nvoid setup() {\n  pinMode(9, OUTPUT);\n}\n\nvoid loop() {\n  for (int value = 0; value <= 255; value++) {\n    analogWrite(9, value);\n    delay(8);\n  }\n  for (int value = 255; value >= 0; value--) {\n    analogWrite(9, value);\n    delay(8);\n  }\n}\n`},
 {id:'pot',name:'Аналоговый мир',desc:'Поверните ручку и наблюдайте показания A0.',level:'Ввод',icon:'sliders-horizontal',parts:[uno,{id:'pot1',type:'pot',x:470,y:160,attrs:{value:512}}],wires:[wire('pot1:VCC','uno:5V','#ef7575'),wire('pot1:GND','uno:GND.2','#829399'),wire('pot1:SIG','uno:A0','#99a9ff')],code:`// Поверните потенциометр на схеме\nvoid setup() {\n  Serial.begin(9600);\n}\n\nvoid loop() {\n  int value = analogRead(A0);\n  Serial.print("A0: ");\n  Serial.print(value);\n  Serial.print(" | ");\n  Serial.print(value * 5.0 / 1023.0, 2);\n  Serial.println(" V");\n  delay(250);\n}\n`},
 {id:'tone',name:'Есть контакт',desc:'Небольшая мелодия на пьезодинамике.',level:'Звук',icon:'music-2',parts:[uno,{id:'bz',type:'buzzer',x:470,y:150,attrs:{}}],wires:[wire('uno:8','bz:2'),wire('bz:1','uno:GND.1','#829399')],code:`// Включите звук в верхней панели\nvoid setup() {\n  pinMode(8, OUTPUT);\n}\n\nvoid loop() {\n  tone(8, 523, 200);\n  delay(250);\n  tone(8, 659, 200);\n  delay(250);\n  tone(8, 784, 400);\n  delay(1500);\n}\n`},
 {id:'servo',name:'Поворот на 180°',desc:'Сервопривод и импульсы управления.',level:'Моторы',icon:'rotate-cw',parts:[uno,{id:'sv',type:'servo',x:455,y:160,attrs:{}}],wires:[wire('uno:9','sv:PWM'),wire('uno:5V','sv:V+','#ef7575'),wire('uno:GND.2','sv:GND','#829399')],code:`// Управление сервоприводом без библиотек\nvoid setup() {\n  pinMode(9, OUTPUT);\n}\n\nvoid loop() {\n  for (int angle = 0; angle <= 180; angle += 2) {\n    int pulse = map(angle, 0, 180, 544, 2400);\n    digitalWrite(9, HIGH);\n    delayMicroseconds(pulse);\n    digitalWrite(9, LOW);\n    delay(20);\n  }\n}\n`}
];
export const makeProject = (example=examples[0]) => structuredClone({version:1,name:example.name,code:example.code,parts:example.parts,wires:example.wires});
export const makeBlankProject = (name='Новый проект') => structuredClone({
 version:1,
 name,
 code:`// Новый проект SIMduino lab\n\nvoid setup() {\n  // Настройте пины здесь\n}\n\nvoid loop() {\n  // Основной код здесь\n}\n`,
 parts:[uno],
 wires:[]
});
